# Introducción a Python

- <a href='#class'>Clasificación General de Tipos de Datos</a> 
- <a href='#tipos'>Tipos de Variables:</a>  
     - <a href='#int'>Numérico entero: `int`</a>
     - <a href='#float'>Númerico decimal: `float`</a>
     - <a href='#string'>Cadena de caracteres: `string`</a>
     - <a href='#bool'>Booleano: `bool`</a>
- <a href='#estru'>Estructuras para organizar datos:</a>
     - <a href='#tuplas'>Tupla: `tuple`</a> 
     - <a href='#listas'>Lista: `list`</a>     
     - <a href='#dic'>Diccionario: `dict`</a>  
- <a href='#numpy'> `NumPy:`</a>  
     - <a href='#arrays'>Arrays (Matrices)</a>
     - <a href='#ols'>OLS with `NumPy`</a>

# <a id='class'>Clasificación General de Tipos de Datos</a> 

| Categoría | Tipo en Python | Descripción | Correspondencia Común en Análisis | Ejemplo de Código |
| :--- | :--- | :--- | :--- | :--- |
| **Numéricos** | `int` | Números enteros sin decimales. | Variables cuantitativas discretas (ej. conteos, frecuencias). | `poblacion = 1500` |
| | `float` | Números con punto decimal (así sea cero). | Variables cuantitativas continuas (ej. tasas, porcentajes, índices). | `tasa_desempleo = 5.8` |
| **Texto** | `str` | Cadenas de caracteres textuales. | Variables cualitativas nominales o texto libre (respuestas abiertas). | `region = "Latam"` |
| **Lógicos** | `bool` | Valores de verdad (`True` o `False`). | Variables dicotómicas o indicadores *dummy* (Sí/No, 0/1). | `es_valido = True` |
| **Secuencias** | `list` | Colecciones ordenadas y **mutables** de elementos. | Vectores de datos, series de observaciones, listas de indicadores. | `edades = [18, 25, 40]` |
| | `tuple` | Colecciones ordenadas e **inmutables** (no modificables). | Estructuras fijas (ej. coordenadas geográficas, constantes). | `coordenadas = (-12.04, -77.03)` |
| **Mapeos** | `dict` | Estructuras de pares `clave: valor`. | Registros complejos, formatos tipo JSON o filas de encuestas. | `sujeto = {"id": 1, "edad": 30}` |
| **Conjuntos** | `set` | Colecciones desordenadas de elementos únicos. | Catálogos de categorías únicas, filtrado de duplicados. | `sectores = {"Salud", "Educacion"}` |
| **Nulos** | `NoneType` | Representa la ausencia de valor (`None`). | Valores faltantes, datos no disponibles (similares a *NaN* o *Null*). | `respuesta = None` |

* **Variables:** Son cntenedores para almacenar valores de datos. La variable tiene una etiqueta o nombre, y es un objeto en la memoria.
* Hay 4 tipos de variable clave en Python: **int, float, string and boolean**.

# <a id='tipos'>Tipos de Variables:</a> 


## <a id='int'>1. Numérico entero: `int`</a>

In [1]:
a = 50

In [2]:
a

50

In [5]:
print(a)

50


In [ ]:
# Tipo numérico entero: int
type(a)

int

## <a id='float'>2. Númerico decimal: `float`</a> 

In [3]:
b = 30.0

In [4]:
print(b)

30.0


In [ ]:
# Tipo numérico flotante: float
# Cuando hay un punto, queda como un float, así haya 0 después del punto.
type(b)

float

## <a id='string'>3. Cadena de caracteres: `string`</a>
* Un string es una secuencia de caracteres. No solo texto.

In [ ]:
# Tipo cadena de caracteres: str
# Al poner comillas, queda como un string (cadena de caracteres) sin importar si es un número o no.
c = "10"
type(c)

str

In [14]:
# El print es importante para mostrar el valor de la variable en la consola en archivos .py, pero no es necesario en notebooks .ipynb.
# Basta con colocar el nombre de la variable en una celda para que se muestre su valor.
# Pero es importante saberlo porque cuando manejemos archivos .py no se mostrará el valor de la variable si no usamos print.
print(c)

10


In [ ]:
# Aquí vemos un ejemplo de texto y números dentro de comillas.
name = "Ulises Rodas 1993"

In [32]:
name

'Ulises Rodas 1993'

In [33]:
# Un string soporta cualquier tipo de caracter, incluso números y símbolos.
my_string = 'hello15%'
print(my_string)

hello15%


In [34]:
# Lo llamamos con comillas dobles o simples
# Veamos un llamado con comillas simples, por lo que las comillas dobles ahora son parte del string.
# Se recomienda simples cuando hagamos scrapeo web, ya que muchas veces los textos contienen comillas dobles.
my_string = ' ""Estamos en 2025"" '
print(my_string)

 ""Estamos en 2025"" 


In [8]:
my_string2 = "Hello%15#$"
print(my_string2)

Hello%15#$


In [9]:
# Las comillas, sean simples o dobles, se ignoran si son consecutivas.
address_rest = ''' La casa rosada "SBA" ''' 
print(address_rest)

 La casa rosada "SBA" 


In [11]:
# Además, se mantiene el formato del texto de origen.
my_string3 = """ Hello, welcome to 
                the world of Python """
print(my_string3)

 Hello, welcome to 
                the world of Python 


In [12]:
my_string4 = """ Hello, welcome to
the world of Python """
print(my_string4)

 Hello, welcome to
the world of Python 


In [15]:
# Cantidad de caracteres:
len(my_string)

21

In [16]:
name = "Jose Felipe"
len(name)

11

In [17]:
# Uniendo:
str_2 = 'Introduction a Python'

print( "Esta clase fue sobre" , str_2 , "dictado por Alexander" )

Esta clase fue sobre Introduction a Python dictado por Alexander


In [18]:
str_1 = "The name"
str_2 = "of the course"
str_3 = "is python"
print(str_1, str_2, str_3)

The name of the course is python


In [19]:
# No se crearán espacios automáticamente si no usamos print.
course_name = str_1 + str_2 + str_3
course_name

'The nameof the courseis python'

In [20]:
# Indexando strings:
# Ubicamos los caracteres de un string por su posición, empezando desde 0.
str = 'Introduction to Python'

In [21]:
str[-2]

'o'

In [22]:
str[2]

't'

## <a id='bool'>4. Booleano: `bool`</a>

The Python Boolean type is one of Python’s built-in data types. It’s used to represent the truth value of an expression. For example, the expression 1 <= 2 is True, while the expression 0 == 1 is False. 

In [ ]:
# Tipo booleano: bool
d = False
type(d)

bool

In [23]:
# En la memoria caché de Pythom, True = 1; False = 0
response = print(10 > 9)
response

True


In [24]:
print(10 == 9)

False


In [25]:
print(10 < 9)

False


In [26]:
# 1 + 0 + 0
# Importante saberlo cuando trabajemos con loops y condicionales
True + False + False

1

In [27]:
True == 1

True

In [28]:
False == 0

True

In [29]:
False == 1

False

In [30]:
True + (False / True)

1.0

# <a id='estru'>Estructuras para organizar datos:</a> 

## <a id='tuplas'>1. Tupla: `tuple`</a>
* Es un contenedor de Python ordenado e inmutable (**no modificable**).
* No podemos cambiar, agregar ni eliminar elementos después de que la tupla ha sido creada. Los elementos de la tupla están ordenados, son inmutables y permiten valores duplicados.
* **Usamos paréntesis.**
* En el día a día no se usa, pero cuando creemos funciones, los outputs son tuplas.

In [ ]:
# Puede *contener* cualquier tipo de objeto:
# Entender que solo almacena información, no puedes modificarla con NumPy ni nada con operaciones.
tuple1 = (1, 2, 5, 9, 10, 10.8, 'PUCP', 'True')
tuple1

(1, 2, 5, 9, 10, 10.8, 'PUCP', 'True')


* Un método siempre irá al costado del nombre del objeto seguido de un punto. 
* Entre paréntesis va lo que queremos buscar:
    * count(): El número exacto.
    * index(): El valor indexado.

| Métodos 	| Definición 	|
|---	|---	|
| count() | Devuelve el número de veces que un valor específico aparece en una tupla. 	|
| index() |	Busca un valor específico en la tupla y devuelve la posición donde fue encontrado. Empieza a contar desde 0.	|


In [37]:
# Sin método, por defecto es una indexación:
tuple1[3]

9

In [ ]:
# Count: Número de veces que se repite del valor indicado
tuple1.count(10)

1

In [ ]:
# Count:
tuple1.count(3)

0

In [ ]:
# Index: Posición del valor indicado
tuple1.index(2)

1

| Función 	| Definición 	|
| --- 	| --- 	|
| type(tuple) 	| It returns the class type of an object. 	|
| max(tuple) 	| It returns an item from the tuple with max value. 	|
| min(tuple) 	| It returns an item from the tuple with min value. 	|
| len(tuple) 	| It gives the total length of the tuple. 	|
| tuple(list) 	| Converts a list into a tuple. 	|

In [38]:
# Las funciones max o min no soportan tuplas con str o bool
tuple2 = (10, 20, 30, 40, 50)
print( type(tuple2) )
print( max(tuple2) )
print( min(tuple2) )
print( len(tuple2) )

<class 'tuple'>
50
10
5


## <a id='listas'>2. Lista: `list`</a>
* Es un contenedor de Python ordenado y mutable (**sí variable**).
* Sus elementos están ordenados, **son modificables**, y permiten valores duplicados y diferentes tipos de objetos.
* Cada elemento tiene un índice porque las listas tienen un orden definido.
* **Usamos corchetes.**

* Igual que en las Tuplas, un método en las Listas siempre irá al costado del nombre del objeto seguido de un punto.

| Métodos 	| Definición	|
|---	|---	|
| sort() 	| Sorts the list in ascending order. 	|
| append() 	| Adds a single element to a list. <br> This element will be located at the end of the list. 	|
| extend() 	| Adds multiple elements to a list. 	|
| index() 	| Returns the first appearance of the specified value. 	|


In [82]:
list0 = ["Ulises", "a#4/", 10, 10.8, True]
list0

['Ulises', 'a#4/', 10, 10.8, True]

In [40]:
list1 = [10, 30, 5, 25, 7]
list1

[10, 30, 5, 25, 7]

In [41]:
# Igual que en las Tuplas, los métodos se llaman con los puntos después del nombre del objeto.
# Método sort: Ordenar de manera ascendente.
list1.sort()
list1

[5, 7, 10, 25, 30]

In [42]:
# También funciona con texto.
list2 = ["Ulises", "Flor de María", "Genaro", "María Elisa"]
list2

['Ulises', 'Flor de María', 'Genaro', 'María Elisa']

In [43]:
list2.sort()
list2

['Flor de María', 'Genaro', 'María Elisa', 'Ulises']

In [44]:
# Podemos agregar elementos: Van al final por defecto.
list2.append("Cosito")
list2

['Flor de María', 'Genaro', 'María Elisa', 'Ulises', 'Cosito']

In [ ]:
# Solo para saber su tipo:

a = [ 18, 20 , 30, "Ulises"]
print(type(a))

<class 'list'>


In [99]:
a[-1]

'Ulises'

**INDEXACIÓN:**
* Es exactamente igual en Tuplas () y Listas [].
* Más detalles, la próxima clase sobre `Pandas`.

In [46]:
# DE TUPLA A LISTA: Usando la función list.
my_tuple = (1, 2, 3, 4, 5)
my_list = list (my_tuple)
my_list

[1, 2, 3, 4, 5]

## <a id='dic'>3. Diccionario: `dict`</a>

It is a ordered (Python >= 3.7) and mutable Python container. It does not allow duplicate key. They must be unique.

| Métodos	| Definición 	|
| --- 	| --- 	|
|clear()|	Removes all the elements from the dictionary|
|copy() |	Returns a copy of the dictionary|
|fromkeys() |	Returns a dictionary with the specified keys and value|
|get() |	Returns the value of the specified key|
|items() |	Returns a list containing a tuple for each key value pair|
|keys() | Returns a list containing the dictionary's keys|
|pop() | Removes the element with the specified key|
|popitem() | Removes the last inserted key-value pair|
|setdefault() | Returns the value of the specified key. <br> If the key does not exist: insert the key, with the specified value|
|update() |	Updates the dictionary with the specified key-value pairs |
|values() | Returns a list of all the values in the dictionary|

* Al igual que en las Tuplas y Listas, los métodos siempre irán al costado del nombre del objeto seguido de un punto
* Los diccionarios son la base de los json files (javascript scripts). 
* Un archivo json es la concatenación de muchos diccionarios, siendo una de las fuentes de base de datos más importantes:
    * APIs
    * Scrapeo web
    * Mapas

* También son contenedores de información al igual que las Tuplas o Listas, pero los diccionario nos permite reconocer la información a través de llaves {}

In [47]:
# Antes de los dos puntos: Keys o llave.
# Después de los dos puntos: Valor asignado a esa llave.
# Recalcar que el diccionario puede contener cualquier tipo de objeto.
Ulises = { "Nombre":"Ulises", "Apellido": "Rodas", "Edad": 33, "Nacimiento": "Callao", "Sexo": True }
Ulises

{'Nombre': 'Ulises',
 'Apellido': 'Rodas',
 'Edad': 33,
 'Nacimiento': 'Callao',
 'Sexo': True}

In [48]:
# Si tengo duda qué tipo de objeto es, puedo llamar a la función type.
type(Ulises)

dict

In [49]:
# Veamos todas las llaves.
Ulises.keys()

dict_keys(['Nombre', 'Apellido', 'Edad', 'Nacimiento', 'Sexo'])

In [ ]:
# Llamo a una llave en particular.
Ulises["Nacimiento"]

'Callao'

In [107]:
Ulises["Sexo"]

True

* Podemos decir que con los **keys** identificamos las **variables** de nuestra data:

In [57]:
# Dictionary containing the population of the 5 largest german cities
population = {'Berlin': 3748148, 'Hamburg': 1822445, 
              'Munich': 1471508, 'Cologne': 1085664, 
              'Frankfurt': 753056 }

In [58]:
population["Munich"]
# population.get('Munich')

1471508

In [59]:
print(population)

{'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056}


In [ ]:
# Limpiamos el diccionario:
# population.clear()
# print( population )

{}


In [60]:
# Vemos todos los elementos del diccionario.
# El resultado contiene múltiples tuplas, cada una agrupando una llave con su respectivo valor.
# El contenedor principal dict_items es una lista. 
# En síntesis, es una lista con múltiples tuplas. Pero sin dejar de ser del tipo diccionario.
population.items()

dict_items([('Berlin', 3748148), ('Hamburg', 1822445), ('Munich', 1471508), ('Cologne', 1085664), ('Frankfurt', 753056)])

In [61]:
# Elimina el último item.
population.popitem()
print(population)

{'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664}


In [62]:
# Actualizamos con nuevos valores (van al final):
population.update({"Bonn": 327258 })
population.update({"Ulm": 100000 })
population

{'Berlin': 3748148,
 'Hamburg': 1822445,
 'Munich': 1471508,
 'Cologne': 1085664,
 'Bonn': 327258,
 'Ulm': 100000}

In [63]:
# Verificamos las nuevas llaves
population.keys()

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Bonn', 'Ulm'])

In [64]:
# Obtener los valores de las llaves
population.values()

dict_values([3748148, 1822445, 1471508, 1085664, 327258, 100000])

# <a id='numpy'>`NumPy`:</a>
* `NumPy` es la biblioteca fundamental para la computación científica en Python. 
* Proporciona vecitres y matriz multidimensionales de alto rendimiento, así como herramientas para trabajar con dichas matrices.

## <a id='arrays'>1. Arrays (Matrices)</a>
* Un array de `NumPy` es una cuadrícula de valores todos del mismo tipo, indexada mediante una tupla de enteros no negativos. 
* El número de dimensiones constituye el rango del array; la forma (*shape*) de un array es una tupla de enteros que indica el tamaño del array a lo largo de cada dimensión.
* Hay que importar la librería antes.

In [67]:
import numpy as np

In [211]:
# [1, 2, 3, 4, 5]

In [68]:
# Vector: Conjunto de solo números (int o float).
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [69]:
# Usar print(a) y a presentan diferentes los resultados, pero quieren decir lo mismo: ambos son vectores.
print(a)

[1 2 3 4 5]


In [70]:
# 2D array (matriz)
M = np.array( [ [1, 2, 3, 5], [4, 5, 6, 10], [4, 5, 6, 10] ] )

M

array([[ 1,  2,  3,  5],
       [ 4,  5,  6, 10],
       [ 4,  5,  6, 10]])

In [71]:
print(M)

[[ 1  2  3  5]
 [ 4  5  6 10]
 [ 4  5  6 10]]


In [72]:
# Filas x Columnas
M.shape

(3, 4)

|Funciones|	Descripción|
| --- |--- |
|np.array(a) |	Create -dimensional np array from sequence a|
|np.linspace(a,b,N) |	Create 1D np array with N equally spaced values <br> from a to b (inclusively)|
|np.arange(a,b,step) |	Create 1D np array with values from a to b (exclusively) <br> incremented by step|
|np.zeros(N)	| Create 1D np array of zeros of length |
|np.zeros((n,m)) |	Create 2D np array of zeros with  rows and  columns|
|np.ones(N) |	Create 1D np array of ones of length |
|np.ones((n,m))|	Create 2D np array of ones with  rows and  columns|
|np.eye(N)	| Create 2D np array with  rows and  columns  <br> with ones on the diagonal  (ie. the identity matrix of size )|
|np.concatenate( )|Join a sequence of arrays along an existing axis|
|np.hstack( )|Stack arrays in sequence horizontally(column wise)|
|np.vstack( )|Stack arrays in sequence vertically(row wise)|
|np.column_stack( )|Stack 1-D arrays as columns into a 2-D array|
|np.random.normal() | Draw random samples from a normal (Gaussian) distribution. |
|np.linalg.inv() | Compute the (multiplicative) inverse of a matrix. |
|np.dot() / @  | Matrix Multiplication. |

* Después del método son las **Funciones**, no métodos (pese a ir después del punto, igual que las Tuplas, Listas o Diccionarios.)
* Truco para diferenciarlos según la palabra antes del punto:
    * Si una **variable (objeto)** que tú creaste con datos (como una lista, un texto o un número), lo que sigue es un **método**.
    * Si es del **apodo de una librería** que importaste (como np para `NumPy`, pd para `Pandas`, o `math`), lo que sigue es una **función** que estás pidiendo prestada de esa librería.

In [73]:
# Crea una matriz de ceros de tamaño (5, 10) :
# Usamos la función zeros de Numpy: Crea una matriz de ceros de tamaño (5, 10). Esto significa que la matriz tendrá 5 filas y 10 columnas, y todos sus elementos serán inicializados a cero.
M = np.zeros((5, 10))
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
M.shape

(5, 10)

In [74]:
# Crear una matriz de 1 dimensión con 10 números 1
# Función ones de Numpy: Crea una matriz de 1 dimensión con 10 números 1. Esto significa que la matriz tendrá 10 elementos, todos inicializados a 1.
w = np.ones(10)
print(w)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [75]:
# Crear una matriz 2D con columnas 5x5 con números 1
N = np.ones( (5, 5) )
print(N)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Crear una matriz identidad de tamaño 10:
# Función eye de Numpy: Crea una matriz identidad de tamaño 10.
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
print(I.shape)
print(I.size)

(10, 10)
100


## <a id='ols'>2. OLS with `NumPy`</a>

In [ ]:
x0.reshape(-1, 1).shape

In [ ]:
# X data generation
n_data = 200
x1 = np.linspace(200, 500, n_data)
x0 = np.ones(n_data)
X = np.hstack(( x0.reshape(-1, 1 ) , x1.reshape(-1, 1 ) ))
X.shape

In [ ]:
# select parameters
beta = np.array([5, -2]).reshape(-1, 1 )
beta.shape

In [ ]:
# y ture
y_true = X @ beta
y_true.shape

In [ ]:
y_true

In [ ]:
y_true + (np.random.normal(0, 1, n_data) * 20).reshape(-1, 1)

In [ ]:
#   add random normal noise
sigma = 20
y_actual = y_true + (np.random.normal(0, 1, n_data) * sigma).reshape(-1, 1)
print(y_actual[0:4, :])

The matrix equation for the estimated linear parameters is as below:
$${\hat {\beta }}=(X^{T}X)^{-1}X^{T}y.$$

In [ ]:
# estimations
beta_estimated = np.linalg.inv(X.T @ X) @ X.T @ y_actual

In [ ]:
import matplotlib.pyplot as plt

plt.plot(x1, y_actual, 'o')
plt.plot(x1, y_true, 'g-', c = 'black')

Calculate the sum of squared residual errors
$$
RSS=y^{T}y-y^{T}X(X^{T}X)^{{-1}}X^{T}y
$$

In [ ]:
y_actual

In [ ]:
RSS = ( y_actual.T @ y_actual - y_actual.T @ X @ np.linalg.inv(X.T @ X) @ X.T @ y_actual )

Calculated the Total Sum of Squares of the spread of the actual (noisy) values around their mean
$$
TSS=(y-{\bar  y})^{T}(y-{\bar  y})=y^{T}y-2y^{T}{\bar  y}+{\bar  y}^{T}{\bar  y}
$$

In [ ]:
y_mean = ( np.ones(n_data) * np.mean(y_actual) ).reshape( -1 , 1 )
TSS = (y_actual - y_mean).T @ (y_actual - y_mean)
TSS

In [ ]:
# get predictions
y_pred = X @ beta_estimated

Calculate the Sum of Squares of the spread of the predictions around their mean.
$$
ESS=({\hat  y}-{\bar  y})^{T}({\hat  y}-{\bar  y})={\hat  y}^{T}{\hat  y}-2{\hat  y}^{T}{\bar  y}+{\bar  y}^{T}{\bar  y}
$$

In [ ]:
ESS = (y_pred - y_mean).T @ (y_pred - y_mean)

ESS

In [ ]:
TSS, ESS + RSS

Get $R^2$
$$
1 - RSS / TSS
$$

In [ ]:
1 - RSS / TSS

###  Standard error of regression
Calculate the standard error of the regression. We divide by `(n-2)`, because the Expectation of the sum of squares is `(n-2)*sigma^2`.

In [ ]:
sr2 = ( (1 / (n_data - 2)) * (y_pred - y_actual).T  @ (y_pred - y_actual))
sr = np.sqrt(sr2)
sr

### Get variance and covariance Matrix
In order to get the standard errors for our linear parameters, we use the matrix formula below:
$$
Var(β^)=σ^2(X′X)^{-1}
$$

In [ ]:
var_beta = sr2 * np.linalg.inv(X.T @ X)
var_beta

In [ ]:
print(
    f'Std Error for b0 {np.sqrt(var_beta[0, 0])}, \nStd Error for b1 {np.sqrt(var_beta[1, 1])}'
)

In [ ]:
pwd